### ISSUE TITLE
Code for Deep Metric Learning for Ground Images，thank u.

### ISSUE THREAD

**Issue by gityeezy** [randolf-scholz/assorted-hooks#1]
Hello, I am very happy to contact you here. This issue is not about your homepage. Thank you very much for your contribution. When I was reading the literature, I read an article you participated in, "Deep Metric Learning for Ground Images" journals/corr/abs-2109-01569. I am very interested in the algorithm and theory, but I couldn't find the code and specific implementation. So I hope to get your response, and I hope to get the code for study. Thank you very much.

**Comment by randolf-scholz** [comment]
Please contact the first author, you can find their e-mail address in the paper. You shouldn't post off-topic request in random GitHub repositories.
